services:
  postgres:
    image: postgres:17.6
    container_name: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      TZ: Asia/Phnom_Penh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB:-postgres} -U ${POSTGRES_USER:-postgres}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: >
      postgres 
        -c shared_preload_libraries=pg_stat_statements 
        -c pg_stat_statements.track=all 
        -c max_connections=50
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.17.1
    container_name: postgres-exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_URI: postgres:5432/postgres?sslmode=disable
      DATA_SOURCE_USER: postgres
      DATA_SOURCE_PASS: postgres
      TZ: Asia/Phnom_Penh
    command:
      - "--collector.postmaster"
      - "--collector.process_idle"
      - "--collector.long_running_transactions"
      - "--collector.stat_statements"
    depends_on:
      prometheus:
        condition: service_started
      postgres:
        condition: service_healthy
    restart: unless-stopped
  redis:
    image: redis/redis-stack-server:7.2.0-v18
    container_name: redis
    restart: on-failure
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes", "--protected-mode", "no" ]
    volumes:
      - ./data/redis:/data
  rabbitmq:
    image: rabbitmq:4.1.3-management-alpine
    container_name: rabbitmq
    restart: on-failure
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-rabbitmq}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-rabbitmq}

  minio:
    image: bitnami/minio:2025.4.22
    container_name: minio
    restart: on-failure
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        minio server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
      MINIO_PROMETHEUS_AUTH_TYPE: public
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Console UI
    volumes:
      - ./data/minio:/data
  loki:
    image: grafana/loki:3.5.2
    container_name: loki
    restart: on-failure
    command: [ "-config.file=/etc/loki/config.yaml", "-config.expand-env=true" ]
    volumes:
      - ./docker/mon/loki/config.yaml:/etc/loki/config.yaml
      - ./data/loki:/loki
    ports:
      - "3100:3100"
    depends_on:
      - minio
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    restart: on-failure
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/mon/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  tempo:
    image: grafana/tempo:2.8.2
    container_name: tempo
    restart: on-failure
    command: [ "-config.file=/etc/tempo.yaml", "-target=all" ]
    volumes:
      - ./docker/mon/tempo/tempo.yml:/etc/tempo.yaml
      - ./data/tempo:/tmp/tempo
    ports:
      - "9411:9411" # zipkin
      - "4317:4317" # OTLP gRPC
  pyroscope:
    image: grafana/pyroscope:1.14.0
    container_name: pyroscope
    restart: on-failure
    command: [ "-config.file=/etc/pyroscope/config.yaml" ]
    volumes:
      - ./docker/mon/pyroscope/config.yaml:/etc/pyroscope/config.yaml
      - ./data/pyroscope:/var/lib/pyroscope
    ports:
      - "4040:4040"
  grafana:
    image: grafana/grafana:12.1.1
    container_name: grafana
    restart: on-failure
    volumes:
      - ./docker/mon/grafana:/etc/grafana/provisioning/datasources
      - ./data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"